# Generated by Django 5.2.8 on 2025-11-09 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity', models.FloatField(default=0)),
                ('relevance', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('completeness', models.FloatField(default=0)),
                ('sentiment', models.CharField(default='neutral', max_length=20)),
                ('empathy', models.FloatField(default=0)),
                ('fallback_count', models.IntegerField(default=0)),
                ('resolution', models.BooleanField(default=False)),
                ('escalation', models.BooleanField(default=False)),
                ('response_time', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analysis_app.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analysis_app.conversation')),
            ],
        ),
    ]
