# Generated by Django 5.2.8 on 2025-11-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
    ]
